name: .NET Core

on: [push]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/softwell-ru/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Confirmation
        run: | 
          cd src\FpML.Pure
          dotnet pack FpML.Confirmation.csproj -c Release -o ../../out
      
      - name: Build Pretrade
        run: | 
          cd src\FpML.Pure
          dotnet pack FpML.Pretrade.csproj -c Release -o ../../out
      
      - name: Build Spfi
        run: | 
          cd src\FpML.SPFI
          dotnet pack -c Release -o ../../out      
           
      - name: Build Spfi Fix
        run: | 
          cd src\FpML.SPFI_FIX
          dotnet pack -c Release -o ../../out      

      - name: Build NSD
        run: | 
          cd src\FpML.NSD
          dotnet pack -c Release -o ../../out

      - name: Build FIXML
        run: | 
          cd src\FIXML
          dotnet pack -c Release -o ../../out

      - name: Push Confirmation to GitHub registry
        run: until dotnet nuget push .\out\FpML.Confirmation.* --skip-duplicate; do echo "Retrying"; sleep 1; done 
        
      - name: Push Pretrade to GitHub registry
        run: until dotnet nuget push .\out\FpML.Pretrade.* --skip-duplicate; do echo "Retrying"; sleep 1; done
        
      - name: Push NSD to GitHub registry
        run: until dotnet nuget push .\out\FpML.NSD.* --skip-duplicate; do echo "Retrying"; sleep 1; done

      - name: Push SPFI to GitHub registry
        run: until dotnet nuget push .\out\FpML.SPFI.* --skip-duplicate; do echo "Retrying"; sleep 1; done

      - name: Push SPFI_FIX to GitHub registry
        run: until dotnet nuget push .\out\FpML.SPFI_FIX.* --skip-duplicate; do echo "Retrying"; sleep 1; done

      - name: Push FIXML to GitHub registry
        run: until dotnet nuget push .\out\FIXML.* --skip-duplicate; do echo "Retrying"; sleep 1; done
