name: .NET Core

on: [push]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/softwell-ru/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Fpml
        run: | 
          cd src
          dotnet pack -c Release -o ../out

      - name: Push Fpml to GitHub registry
        run: dotnet nuget push ./out/*.snupkg --skip-duplicate --no-symbols true -s "https://nuget.pkg.github.com/softwell-ru/index.json"
      