name: Publish nuget packages

on:
  push:
    branches: [dev, release/*]
  workflow_dispatch:

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - name: Restore dependencies
        run: dotnet restore --no-cache
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - name: Pack
        run: dotnet pack -c Release -o packages
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - name: Push packages to nuget
        shell: bash
        run: |
          until dotnet nuget push ./packages/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate; do echo "Retrying"; sleep 1; done
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
